Root:
  app_name: DaleelPetroAgent

ConversationConfig:
  conversational_history_db: data/conversations.db

ContentConfig:
  max_output_tokens: 4096
  temperature: 0.3
  thinking:
    max_output_tokens: 1024
    include_thoughts: false

LLmConfig:
  model_name: gemini-2.5-flash
  api_keys: 
    - GOOGLE_API_KEY
    - GOOGLE_API_KEY_2
    - GOOGLE_API_KEY_3
  description: Daleel Petroleum Contract Evaluation Agent

SessionConfig:
  max_messages: 20
